FuelLabs/forc-wallet

src/account.rs, src/list.rs, src/utils.rs
closes #22.
I am planning to tackle #5 and this one is slightly relative as this changes the way we store list of derived account addresses. With #19 we were just holding the number of derived accounts so far and while listing we were deriving them all. With this PR, we are storing their public addresses so that we don't need to decrypt the wallet just to show the list of accounts.
=> refactor: list accounts without decrypting the wallet

src/account.rs, src/main.rs
closes #5.
Introduces `account` command which can be used for getting an account's public address from it's index.
```sh
forc-wallet account <account-index>
```
Example run:
```sh
$ forc-wallet account 0
Account 0 address: 0xfuel1nrtj75vvl6hp6czl0yhpe5p78qfud7fuk6gffekgtk58nkqn0j5qft8y7s
```
=> feat: added `account` command to show address of an account given its index

Cargo.lock, Cargo.toml, src/account.rs, src/list.rs, src/main.rs, src/sign.rs, src/utils.rs
closes #7.
This PR introduces a new command `sign` to the `forc-wallet`. Currently `sign` accepts 2 parameters:
1. Transaction id
2. Account index of the account that we want to sign this transaction with
In this first iteration of development (where we are trying to enable our users to sign deployment transactions) The usual signing process while deploying a contract currently looks like the following:
1. Running `forc-deploy` will ask the user to input the address of the wallet they are going to be signing with. To get that the user can either run the `forc-wallet list` and look under the `address` section of the desired account or run `forc-wallet account <account_index>` to get the address. This reports a transaction id and waits for the signature.
2. User runs `forc-wallet sign …
=> feat: add the sign feature

.github/workflows/ci.yml
Version 0.1.0 was published with an out-of-date lock file. This updates CI to ensure it's always at least up to date with the `Cargo.toml` requirements.
=> Adds a CI check to ensure the lock file is always up to date

src/account.rs, src/main.rs
closes #39.
This PR adds `--export` to `forc-wallet account` so that people can get their private key from their accounts managed by `forc-wallet` and use import and use them in SDKs. To not leak any private key in the terminal history it is shown in an alternate screen just like the seed phrase.
=> feat: Add --export to account to export account's private key

.github/workflows/ci.yml
=> CI: build binaries in CI

src/account.rs, src/export.rs, src/main.rs
=> feat: Moved --export to a seperate export command

Cargo.lock, Cargo.toml
=> Bump version to v0.1.1

src/export.rs, src/import.rs, src/init.rs, src/main.rs, src/utils.rs
closes #52.
closes #53.
Also slightly improves the error message for existing vault path.
Since these are affecting our users rn, I wanted to get them out as soon as possible hence they are in the same PR.
=> Fix error in the case of an non-existing vault path and refactor discrete string utility

Cargo.lock, Cargo.toml, src/account.rs, src/export.rs, src/import.rs, src/init.rs, src/list.rs, src/main.rs, src/sign.rs, src/utils.rs
This PR adds tests for basic wallet functionalities that we have now. To do so I needed to separate CLI and actual logic so that I could add tests for the logic. Also I tried to refactor the code such for passing around `Path` to the logic functions, ~I used `AsRef<Path>` so that if we decide to consume this crate as a lib for `forc-client` etc, API is as accepting as possible~.
I needed serial tests as for the tests I am generating and removing a tmp directory. Since by default `cargo test` works in parallel, different tests can remove the folder created for other tests. To overcome this I can either run the tests in parallel but create different directories for each test or the tests that needs a tmp dir will need to work serially. Since tests are pretty quick I followed the serial …
=> test/refactor: Add tests for existing wallet operations and split CLI and the actual logic

README.md
In commit 217c466 the import argument was moved to a separate command, the current README does not reflect that.
=> import is own command and not anymore a argument

src/utils.rs
- Removed needless borrow in one place so that CI would still pass for branches forked from master
=> chore: clippy warnings for rust 1.66.1

README.md, src/account.rs, src/export.rs, src/import.rs, src/init.rs, src/list.rs, src/main.rs, src/sign.rs, src/utils.rs
Closes #76.
Previously each subcommand had it's own instance of the `--path` argument. Instead, we now expect the `--path` argument on the top-level command, e.g.
```console
forc wallet --path ./path/to/wallet list
```
rather than
```console
forc wallet list --path ./path/to/wallet
```
By coupling the arg with the `wallet` command we also make the association a bit clearer.
This PR also refactors a lot of the utility functions to use "wallet" when referring to the wallet directory, rather than "vault". Before, the two were used interchangeably which could cause some confusion for future maintainers.
=> Refactor `--path` arg for commands, use consistent terminology for wallet directory

src/account.rs, src/main.rs
*PR based on #84.*
Closes #77 as the main concern with storing addresses in plain text is that it makes them an easy target of corruption.
This PR changes the behaviour of the `forc wallet accounts` and `forc wallet account <ix>` commands to always require a password by default. This ensures the printed addresses are valid. This was tricky to guarantee in the old behaviour as the cached plain-text files could have been corrupted or maliciously altered since they were last written.
Both commands now accept an `--unverified` flag that emulates the old behaviour and purely reads the addresses from the cache.
=> Add `--unverified` option to commands that display cached addresses

Cargo.lock, Cargo.toml, README.md, src/account.rs, src/main.rs, src/sign.rs, src/utils.rs
This PR allows the user to sign arbitrary data. Here are some examples taken from the help output:
```console
forc wallet account 3 sign string "blah blah blah"
forc wallet account 3 sign file /path/to/data-to-sign
forc wallet account 3 sign hex "0xDEADBEEF"
```
This PR also re-introduces the `forc wallet sign` subcommand. This re-uses the existing logic for signing via the account subcommand, though provides the additional option of signing with a private key. Some examples:
```console
forc wallet sign --account 3 string "blah blah blah"
forc wallet sign --private-key string "blah blah blah"
```
Notably, this PR also removes the old `forc wallet sign-private` command in favour of using `forc wallet sign --private-key` in order to try and provide a more uniform interface.
The `sign tx` …
=> feat: Add support for signing arbitrary data via new `string`, `file` or `hex` subcommands

Cargo.lock, Cargo.toml
I'll include the following in the release notes too.
The `forc wallet` CLI has had a significant overhaul! Notably:
* To create a new wallet, use `forc wallet new` rather than `forc wallet init`.
* To derive a new account, use `forc wallet account new` rather than `forc wallet new`.
* To list all previously derived accounts, use `forc wallet accounts` rather than `forc wallet list`.
* The old `--account-index` flag has been removed in favour of the `account` subcommand, e.g. * To sign a tx ID with an account, use `forc wallet account <ix> sign tx-id` rather than `forc wallet sign --account-index <ix> --tx <tx-id>`. * To export an account private key, use `forc wallet account <ix> private-key` rather than `forc wallet export --account-index<ix>`.
* The `forc wallet accounts` command now …
=> Publish v0.2.0

README.md, src/account.rs, src/main.rs
closes #91.
This PR is adding `public-key` subcommand to `account` command. 
Example usage is:  `forc-wallet account <account_index> public-key`
=> feat: add support for displaying public key for an account derived with `forc-wallet`

Cargo.lock, Cargo.toml, src/account.rs, src/import.rs, src/main.rs, src/new.rs, src/utils.rs
Show the balance of the specified account:
```console
forc wallet account <ix> balance
```
Show the total balance for the whole wallet:
```console
forc wallet balance
```
Show the balance of each non-empty account prior to the wallet total:
```console
forc wallet balance --accounts
```
Demo:
```console
$ forc wallet account 0 balance
Please enter your password to verify account 0:
Verifying account 0
Connecting to https://node-beta-2.fuel.network/
Fetching the balance of the following account:
0: fuel1htrldg7wpelrnhvad8lwcep57duhpxmj2h6a55nhr4md4839cy2q04p3tu
Account 0:
Asset ID                                                           Amount
0x0000000000000000000000000000000000000000000000000000000000000000 1000000000
$ forc wallet account 1 balance
Please enter your password to verify …
```
=> Add `balance` and `account <ix> balance` subcommands for printing all asset balances

src/account.rs, src/main.rs
@bingcicle I'm thinking we probably want to release a new `forc-wallet` version and bump fuelup's beta-3 toolchain version too. I'll cut a patch release as a follow-up.
=> Add beta-3 network URL. Switch to beta-3 as the default.

src/account.rs
By default, we are given the Bech32 format of the public key from the forc-wallet account command, whereas, for Sway, it is required that we use a plain address in the contract. For the convenience of developers, I rigged up the functionality to derive the plain address directly from the CLI with a unit test that sanity checks the type conversion.
=> Add derivation for plain address into forc-wallet

Cargo.lock, Cargo.toml, src/account.rs, src/main.rs
Closes #65 
I took the liberty to name the command `transfer` instead of `send` to keep consistent with what's available in `fuels_signers`: https://docs.rs/fuels-signers/0.38.1/fuels_signers/wallet/struct.WalletUnlocked.html#method.transfer
Also added an additional feature that shows TX on the block explorer for convenience.
Preview:
=> feat: transfer

Cargo.toml, src/account.rs, src/balance.rs, src/import.rs, src/lib.rs, src/main.rs, src/new.rs, src/sign.rs
closes #100.
In a recent tooling sync we talked about splitting lib functionality of `forc-wallet` into two parts:
1. Exposing cli bindings
2. Exposing all the functionality as pure functions (which does not require any CLI interaction)
This completes the first part, any `forc-wallet` command that is useable from CLI should also be useable consuming `forc-wallet` as lib with this PR.
=> feat: expose cli functionality as a lib

src/account.rs, src/balance.rs, src/lib.rs
This PR exposes some balance related functionality so that `forc-deploy` can use them to print and collect account information for balance queries.
=> refactor: expose balance collecting and printing functionality

src/balance.rs
closes #122.
This was caused by a breaking change, in clap. [Here](https://github.com/clap-rs/clap/discussions/4306) is a discussion in clap's repo for the solution.
=> fix: forc-wallet balance command panics after clap v4 update

src/account.rs, src/lib.rs
closes #133.
With this PR `forc-wallet` points to beta-4 network by default. ~Waiting for block explorer URL to be confirmed.~
=> feat: point to beta-4 faucet and block explorer by default

Cargo.lock, Cargo.toml
Publishing v0.3.0 forc-wallet which supports beta-4 network.
=> chore: bump to v0.3.0

Cargo.lock, Cargo.toml, src/account.rs
We no longer need to provide default values from sdk as:
> Changes gas_limit and gas_price in TxParams to be optional. TransactionBuilders use the corresponding values from ConsensusParameters and NodeInfo during build() if these fields were set to None.
https://github.com/FuelLabs/fuels-rs/pull/1121
=> chore: bump fuels-rs to 0.49

Cargo.lock, Cargo.toml
This PR upgrades fuels-rs crates used here to v0.50.1
=> chore: upgrade to fuels-rs v0.50.1

Cargo.lock, Cargo.toml, src/import.rs, src/main.rs, src/new.rs, src/utils.rs
=> feat: add --force option to forc-wallet new

Cargo.lock, Cargo.toml
Bumps sdk version to 0.54.0 for unblocking a fix for https://github.com/FuelLabs/sway/issues/5432
=> chore: bump sdk version to 0.54.0

src/new.rs
It turns out we need it for forc-client as new options changed since last release and I failed to realize
=> chore: expose new options for new_cli so that it can be used outside this repo

src/account.rs, src/utils.rs
close #150
Refer to [Comment](https://github.com/FuelLabs/forc-wallet/pull/148#discussion_r1410041380)
I have reviewed whole forc-wallet project codes, all warning output that using `println!` has changed to `println_warning`
----
=> refactor: use common forc utils for formatting error & warning output

src/account.rs, src/lib.rs
Beta-5 endpoint is ready forc-wallet should point to that by default without needing our users to use a flag to point out beta-5.
=> feat: point to beta-5 by default

Cargo.lock, Cargo.toml
This will break compatibility with beta-5.
=> chore: bump to sdk 0.56.0, vm 0.47

Cargo.lock, Cargo.toml
bumps rust sdk version used to v0.62.0
=> chore: bump fuels-rs to 0.62.0

Cargo.lock, Cargo.toml
Bumps the repo to use fuel-core v0.27.0 and rust-sdk v0.63.0
=> chore: bump to fuel-core v0.27.0

Cargo.lock, Cargo.toml
Bumps sdk version used to 0.64.0, to support fuel-core v0.28.0
=> chore: bump sdk to 0.64.0 to support fuel-core v0.28.0

Cargo.lock, Cargo.toml
Made this a minor bump as fuel-core compatibility is not effected from v0.8.0, also no breaking api changes.
=> chore: bump to v0.8.1

Cargo.lock
It has been some time that we updated dependencies, and also #194 depends on nightly rust being able to build the repo which is only possible with https://github.com/tkaitchuck/aHash/issues/227.
=> chore: update all dependencies

.github/workflows/ci.yml
closes #193.
Adds code coverage reporting step to CI. Once we have #192 merged, coverage should increase dramatically.
=> ci: add code coverage reports

Cargo.lock, Cargo.toml
Starts the process to update our whole stack to fuel-core v0.31.0
=> chore: bump to use sdk 0.65

src/account.rs, src/balance.rs, src/list.rs
closes #198.
We are now printing plain addressed from forc-wallet if bech32 is not explicitly requested by the user.
=> feat: print plain addresses by default

Cargo.lock, Cargo.toml
Updates fuels-* to v0.66.5 to support fuel-core v0.36.5
=> chore: bump fuels-* to v0.66.5

Cargo.lock, Cargo.toml, src/account.rs, src/balance.rs, src/lib.rs, src/list.rs, src/main.rs
This PR implements couple of things:
1. Adds a new target
2. Adds checksum routines at places where we print user account, and accept user account (transfer to address).
3. Bumps sdk version to latest, 0.66.8.
1. At the places where we output hex address we now output checksum encoded hex address so that copied and pasted into any other wallet, users will not face any warning. 
2. At places where we accept a user account address, (currently only `transfer`'s `to` field), we query the provider to see if this account actually belongs to an user (i.e it is not a blob id, contract id etc).
I needed to add an unwrap, at a place where I am sure that the result is not going to be failing. After this release I will remove it by rewriting the transfer section of the wallet.
We first check if the …
=> feat: implement check sum reporting and update default target

Cargo.lock, Cargo.toml
=> chore: bump sdk to v0.66.9

src/import.rs
- `force` var in the `Import` struct made public
This is required to address https://github.com/FuelLabs/forc-wallet/issues/139 as we need to support importing wallet - which requires instantiating the `Import` struct
=> Import struct force var public visibility

.github/workflows/ci.yml, .github/workflows/markdown-lint.yml, .gitignore, Cargo.lock, Cargo.toml, rust-toolchain.toml, src/account.rs, src/utils.rs
- added [`tempfile`](https://crates.io/crates/tempfile) to create test dirs for testing
- updated test functions and util functions accordingly (removed redundant helper functions and replaced references)
- added `rust-toolchain.toml` with stable rust `1.80.0`
- minor refactors to CI workflows to match the `rust-toolchain.toml` rust version
- git ignoring IDE directory (`.vscode/`)
- fixed `new_at_index` function to print checksum wallet address (currently printing bech32 address to stdout)
- updated `ensure_no_wallet_exists` function to handle the following cases:
- where wallet path is a directory
- where wallet path is an empty file
- this also addresses: https://github.com/FuelLabs/forc-wallet/issues/186
- added unit tests for `ensure_no_wallet_exists`
=> Fix minor wallet issues

src/export.rs, src/lib.rs, src/main.rs
closes #237
Adds `forc-wallet export`  and `forc-wallet export --path <PATH>` command to be able to export mnemonic phrase so that it can be imported to the browser wallet.
=> feat: wallet export

Cargo.lock, Cargo.toml
This pull request includes a version update for the `forc-tracing` dependency in the `Cargo.toml` file.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L14-R14): Updated the `forc-tracing` dependency from version `0.67` to `0.68`.
=> upd forc-tracing 0.67.0 -> 0.68.8
