FuelLabs/forc-wallet

README.md

Update readme with installation and basic usage

---

Cargo.toml

As a result of our discussion with @mitchmindtree, converted to draft to add a better readme before going for a release

bump to v0.1.0

---

Cargo.lock
README.md
src/init.rs
src/main.rs

feat: Accept optional phrase as a password field rather than a parameter

---

src/import.rs
src/main.rs

feat: Move init --import to a seperate command (import)

---

Cargo.lock
Cargo.toml
src/account.rs
src/import.rs
src/init.rs

bump fuels versions to 0.24.0

---

src/account.rs
src/utils.rs

refactor: Use SDK derivation path

---

src/account.rs
src/export.rs
src/import.rs
src/init.rs
src/list.rs
src/main.rs
src/sign.rs
src/utils.rs

This is just a small PR to "get out" some work I had done earlier, I will probably not do more work on this repo unfortunately, the SDK needs me :smile:

refactor: rework some basic functions

---

Cargo.lock
Cargo.toml

bump version to 0.1.2

---

README.md

doc: Add export and import to readme

---

README.md

docs: update README quickstart

---

src/main.rs
src/sign.rs
src/utils.rs

feat: sign with private key command for testing with local node

---

Cargo.lock
Cargo.toml

chore: bump version to 0.1.3

---

src/account.rs
src/export.rs
src/init.rs
src/list.rs
src/utils.rs

Rust 1.67.0 is released and there are some new clippy lints to address.

chore: 1.67.0 cargo clippy fix

---

Cargo.lock
Cargo.toml
src/init.rs
src/sign.rs
src/utils.rs

Update all dependencies, removed unused

---

Cargo.lock
Cargo.toml

For releasing #93 to unblock @ra0x3.

chore: bump version to 0.2.1

---

src/account.rs
src/balance.rs
src/sign.rs

Closes #111 
- Added the word `wallet` to each password prompt

Update password input message

---

Cargo.lock
Cargo.toml
src/account.rs
src/balance.rs
src/import.rs
src/new.rs
src/sign.rs
src/utils.rs

chore: bump fuels-* to 0.43 and fuel-* to 0.31

---

README.md
src/sign.rs

feat: enforce 0x prefix for hex data input

---

Cargo.lock
Cargo.toml

~~Blocked by https://github.com/FuelLabs/fuels-rs/pull/997~~

Bump fuels, fuels-core and fuel-* deps

---

Cargo.lock
Cargo.toml

Waiting for:
-  #123
-  #125 
-  #126

chore: bump version to v0.2.4

---

Cargo.lock
Cargo.toml

This pull request is an upgrade to a `fuel-core 0.20.1` release.

An upgrade to `fuel-core` v0.20.1

---

Cargo.lock
Cargo.toml

Upgrade to `tx-policies` branches of:
- `fuels-rs`
- `fuel-vm`
- `fuels-core`

feat: upgrade `fuels-rs` and `fuels-core` to `tx-policies`

---

Cargo.lock
Cargo.toml

To get:
- #140 
- #141 
- #144 
- #145 
- #151

chore: bump version to 0.4.0

---

Cargo.lock
Cargo.toml

Bumps version to v0.4.2 to get:
1. #160

chore: bump version to 0.4.2

---

Cargo.lock
Cargo.toml

chore: bump to v0.4.3

---

Cargo.lock
Cargo.toml

chore: bump fuel-core to v0.24.3

---

Cargo.lock
Cargo.toml

chore: bump to v0.7.1

---

src/account.rs
src/lib.rs

Updates the default end point for balance queries to testnet instead of beta-5.

feat: point to testnet for default query end point

---

Cargo.lock
Cargo.toml

chore: bump to v0.8.0

---

.github/workflows/ci.yml

Also updating the slack webhook URL

chore: Use FuelLabs fork of publish-crates

---

Cargo.lock
Cargo.toml

chore: bump to v0.8.2

---

Cargo.lock
Cargo.toml

Upgraded fuels version and ran `cargo update`

upgrade to fuels v0.66.6 and bump to v0.10.0

---

Cargo.lock
Cargo.toml

- version bump `0.11.0` -> `0.11.1`

chore: bump to 0.11.1

---

src/account.rs
src/lib.rs

Closes https://github.com/FuelLabs/forc-wallet/issues/228

chore: remove beta networks
